### ISSUE TITLE
submit code for hacktoberfest

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/car-racing-game#15]

**Comment by Esha-in-arena** [comment]
@hariom20singh i want to contribute  in this repo. Assign it to me.

**Comment by parthibdhal** [comment]
please assign it to me. i want to complete 4 pull requests

**Comment by codesbysaurav** [comment]
Hello sir,
I would like to contribute my code in C++ for this issue under Hacktoberfest2022.
Could you please assign me with this issue?
Thank you!!
